#!/usr/bin/env zsh
# Renders buildtime.md from the samples in buildtime.csv2.
#
#   zsh buildtime/buildtime.zsh          write buildtime.md
#   zsh buildtime/buildtime.zsh --help
#
# Every row is one measured build. The table reports the SAMPLE COUNT beside
# every range, because a range without a count is not a measurement -- "9 to 12
# seconds" from two runs and from twenty runs are different claims, and only one
# of them is worth planning around.
#
# WHY A SAMPLE FILE RATHER THAN A HAND-WRITTEN TABLE. A build time is a snapshot
# of a machine, a toolchain and a dependency graph, and all three move. A table
# someone edits by hand drifts silently; a table generated from dated rows can
# only go stale visibly. Append rows, never rewrite them, and the counter grows
# with the evidence.
#
# 由 buildtime.csv2 中的樣本產生 buildtime.md。
#
# 每一列都是一次實測的建置。表格會在每個範圍旁列出**樣本數**，因為沒有樣本數的範圍稱不上量測——
# 「9 到 12 秒」出自兩次與出自二十次是兩種不同的主張，而只有其中一種值得據以規劃。
#
# 為何採用樣本檔而非手寫表格：建置時間是「機器 × 工具鏈 × 相依圖」的快照，而三者都會變動。手動
# 維護的表格會無聲地失準；由帶有日期的資料列產生的表格，只能以看得見的方式過時。請只追加、不要
# 改寫，計數便會隨證據一同成長。
set -euo pipefail

script_path="${0:A}"
folder="${script_path:h}"
csv="$folder/buildtime.csv2"
md="$folder/buildtime.md"

# Answers before doing any work, so a wrong flag costs a page of text rather
# than a build.
# 在做任何事之前先回答，如此輸錯旗標的代價是一頁文字，而非一次建置。
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    sed -n '2,30p' "$script_path" | sed 's/^# \{0,1\}//'
    exit 0
fi

if [ ! -f "$csv" ]; then
    printf 'buildtime.zsh: %s is missing; it is the sample file and ships with the repo\n' \
        "$csv" >&2
    exit 1
fi

# No `|| printf 0` fallback. `grep -c` prints 0 when nothing matches and exits 1
# at the same time, so the fallback fires too and the count becomes "0\n0".
# 此處不加 `|| printf 0` 的退路：`grep -c` 在無匹配時會印出 0 並「同時」以 1 結束，於是退路也會
# 執行，計數變成 "0\n0" 兩個字元。
rows="$(csv2 -r -i "$csv" 2>/dev/null | grep -c .)"

{
    printf '# Build times / 建置時間\n\n'
    printf 'Generated from `buildtime.csv2` — do not edit this file:\n\n'
    printf '```sh\nzsh buildtime/buildtime.zsh\n```\n\n'
    printf '由 `buildtime.csv2` 產生——請勿編輯本檔。\n\n'
    printf '**Samples recorded / 已記錄樣本數: %s**\n\n' "$rows"

    csv2 -r -i "$csv" --json 2>/dev/null | awk '
        function field(name,   pattern, start, rest, end) {
            pattern = "\"" name "\":\""
            start = index($0, pattern)
            if (start == 0) return ""
            rest = substr($0, start + length(pattern))
            end = index(rest, "\"")
            return end ? substr(rest, 1, end - 1) : ""
        }
        /"record"/ {
            key = field("host") "\t" field("target") "\t" field("scenario")
            v = field("seconds") + 0
            if (!(key in n)) { lo[key] = v; hi[key] = v; order[count++] = key }
            if (v < lo[key]) lo[key] = v
            if (v > hi[key]) hi[key] = v
            sum[key] += v
            n[key]++
        }
        END {
            print "| host | target | scenario | samples | min | mean | max |"
            print "|---|---|---|---:|---:|---:|---:|"
            for (i = 0; i < count; i++) {
                k = order[i]
                split(k, parts, "\t")
                printf "| %s | %s | %s | %d | %.2f s | %.2f s | %.2f s |\n",
                    parts[1], parts[2], parts[3], n[k], lo[k], sum[k] / n[k], hi[k]
            }
        }
    '

    printf '\n## Scenarios / 情境\n\n'
    printf '| scenario | what was done |\n|---|---|\n'
    printf '| `no-op` | build with nothing changed |\n'
    printf '| `single-file` | one line appended to one file in that target |\n'
    printf '| `tree-sync` | first build after `rsync --delete` of the whole `Sources/` tree |\n'
    printf '| `after-shared-edit` | first build after editing `Sources/SwiftCrossUI/` |\n'
    printf '| `full-app` | `testapp/compile.zsh`, app plus everything it links |\n'
    printf '| `session-observed` | taken from ordinary work, not a controlled run |\n'
    printf '\n'
    printf '`session-observed` rows are kept separate on purpose, and the table\n'
    printf 'shows why: on Windows they are FASTER than the controlled\n'
    printf '`single-file` runs, which cannot be true of a real edit-and-rebuild.\n\n'
    printf 'The cause is the command that produced them. It ran the build twice --\n'
    printf 'once piped to `grep error:`, once piped to `tail -1` for the time --\n'
    printf 'so the number reported came from the SECOND run, with nothing left to\n'
    printf 'do. Those rows are mostly no-op builds wearing an edit-build label.\n\n'
    printf 'Kept rather than deleted, because a plausible wrong number is worth\n'
    printf 'recognising: it looked like a normal measurement for a whole session.\n'
    printf 'Do not mix them into a planning figure.\n\n'
    printf '`session-observed` 的資料列刻意分開，而上表正好顯示了原因：在 Windows 上，它們竟比受控的\n'
    printf '`single-file` 更快，而這對於真正的「改一下、再建一次」是不可能的。\n\n'
    printf '原因出在產生它們的那道指令：它把建置跑了兩次——一次導向 `grep error:`、一次導向\n'
    printf '`tail -1` 以取得時間——因此被記下的數字來自**第二次**執行，而那時已無事可做。那些資料列\n'
    printf '多半是掛著「編輯後建置」標籤的 no-op 建置。\n\n'
    printf '此處保留而非刪除，因為「看似合理的錯誤數字」值得被認得出來：它在整個工作階段中，看起來\n'
    printf '都像是一次正常的量測。請勿把它們併入用於規劃的數字。\n'
} > "$md"

printf 'wrote %s (%s samples)\n' "$md" "$rows"
exit 0
