#!/usr/bin/env zsh
# Regenerates mistakes.md from mistakes.csv2.
#
#   zsh mistakes/mistakes.zsh          write mistakes/mistakes.md
#   zsh mistakes/mistakes.zsh --count  just the number
#   zsh mistakes/mistakes.zsh --help
#
# The CSV is the record; the Markdown is a view of it. Editing mistakes.md by
# hand is pointless -- the next run overwrites it. Add a row with:
#
#   csv2 -i mistakes/mistakes.csv2 --in-place \
#        -append '2026-08-28,Area,"claimed","was true","caught by","lesson"'
#
# `csv2` rather than a hand-rolled table, for the reason this project uses it
# everywhere: fields here contain commas, and splitting on `,` mis-aligns
# columns silently rather than failing. The .csv2 format also carries two header
# rows, English then Traditional Chinese, which is what the rest of the project
# writes.
#
# 由 mistakes.csv2 重新產生 mistakes.md。
#
# CSV 才是紀錄本身，Markdown 只是它的一個視圖。手動編輯 mistakes.md 沒有意義——下一次執行就會覆蓋
# 它。新增一列請用上方的 `csv2 -append`。
#
# 使用 `csv2` 而非自己拼表格，理由與本專案各處相同：此處的欄位含有逗號，而以 `,` 切割會靜默地把
# 欄位錯開，而不是失敗。`.csv2` 格式同時帶有兩行標題（英文、繁體中文），與專案其他部分一致。

set -uo pipefail

script_path="${0:A}"
# mistakes/<this> -> mistakes -> repo root
# mistakes/<本檔> -> mistakes -> repo 根目錄
here="${script_path:h}"
repo="${here:h}"
csv="$here/mistakes.csv2"
md="$here/mistakes.md"

if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    sed -n '2,24p' "$script_path" | sed 's/^# \{0,1\}//'
    exit 0
fi

if ! command -v csv2 >/dev/null 2>&1; then
    printf 'mistakes.zsh: csv2 is not on PATH\n' >&2
    exit 1
fi

# Data records only -- `csv2` counts the header as record 0, so no adjustment.
# 只計資料列——`csv2` 把標頭算作第 0 筆，因此無需扣除。
count="$(csv2 -r -i "$csv" 2>/dev/null | grep -c .)"

if [ "${1:-}" = "--count" ]; then
    printf '%s\n' "$count"
    exit 0
fi

{
    printf '# mistakes\n\n'
    printf 'Wrong things I said or did on this project, and what turned out to be true.\n\n'
    printf 'Generated from `mistakes.csv2` — do not edit this file, edit that one:\n\n'
    printf '```sh\nzsh mistakes/mistakes.zsh\n```\n\n'
    printf '本檔記錄我在此專案上說錯或做錯的事，以及實際情況為何。\n\n'
    printf '由 `mistakes.csv2` 產生——請勿編輯本檔，改編輯該 CSV。\n\n'
    printf '**Count / 次數: %s**\n\n' "$count"
    printf 'A counter rather than a score. The useful column is `caught_by`: it says\n'
    printf 'what the cheapest available check would have been, and most of them were\n'
    printf 'available before the claim was made.\n\n'
    printf '這是計數，不是分數。真正有用的欄位是 `caught_by`——它記錄的是「當時最便宜的查證方式是\n'
    printf '什麼」，而其中大多數，在說出那句話之前就已經可以做了。\n\n'

    csv2 -r -i "$csv" -t -md --pretty
} > "$md"

printf 'wrote %s (%s entries)\n' "$md" "$count"
exit 0
