// GENERATED by testapp/plan/tools/generate_symbol_table.py -- do not edit.
// Source of truth: testapp/plan/symbol-table-v1.md
//
// 由 testapp/plan/tools/generate_symbol_table.py 產生——請勿編輯。
// 真實來源:testapp/plan/symbol-table-v1.md

extension SystemSymbol {
    /// Every symbol, in the table's own order.
    /// 全部符號,依表中順序。
    public static let all: [SystemSymbol] = [
        SystemSymbol(
            name: "add",
            sfSymbol: "plus",
            gtkIconName: "list-add",
            segoeScalar: 0xE710,
            androidDrawable: "ic_input_add",
            textFallback: "+"
        ),
        SystemSymbol(
            name: "delete",
            sfSymbol: "trash",
            gtkIconName: "edit-delete",
            segoeScalar: 0xE74D,
            androidDrawable: "ic_delete",
            textFallback: "Delete"
        ),
        SystemSymbol(
            name: "warning",
            sfSymbol: "exclamationmark.triangle",
            gtkIconName: "dialog-warning",
            segoeScalar: 0xE7BA,
            androidDrawable: "ic_dialog_alert",
            textFallback: "!"
        ),
        SystemSymbol(
            name: "info",
            sfSymbol: "info.circle",
            gtkIconName: "dialog-information",
            segoeScalar: 0xE946,
            androidDrawable: "ic_dialog_info",
            textFallback: "i"
        ),
        SystemSymbol(
            name: "phone",
            sfSymbol: "phone",
            gtkIconName: "phone",
            segoeScalar: 0xE717,
            androidDrawable: "ic_dialog_dialer",
            textFallback: "Phone"
        ),
        SystemSymbol(
            name: "mail",
            sfSymbol: "envelope",
            gtkIconName: "mail-message-new",
            segoeScalar: 0xE715,
            androidDrawable: "ic_dialog_email",
            textFallback: "Mail"
        ),
        SystemSymbol(
            name: "map",
            sfSymbol: "map",
            gtkIconName: "find-location",
            segoeScalar: 0xE707,
            androidDrawable: "ic_dialog_map",
            textFallback: "Map"
        ),
        SystemSymbol(
            name: "search",
            sfSymbol: "magnifyingglass",
            gtkIconName: "system-search",
            segoeScalar: 0xE721,
            androidDrawable: "ic_menu_search",
            textFallback: "Search"
        ),
        SystemSymbol(
            name: "lock",
            sfSymbol: "lock",
            gtkIconName: "system-lock-screen",
            segoeScalar: 0xE72E,
            androidDrawable: "ic_lock_idle_lock",
            textFallback: "Lock"
        ),
        SystemSymbol(
            name: "batteryLow",
            sfSymbol: "battery.25",
            gtkIconName: "battery-low",
            segoeScalar: 0xE851,
            androidDrawable: "ic_lock_idle_low_battery",
            textFallback: "Battery"
        ),
        SystemSymbol(
            name: "power",
            sfSymbol: "power",
            gtkIconName: "system-shutdown",
            segoeScalar: 0xE7E8,
            androidDrawable: "ic_lock_power_off",
            textFallback: "Power"
        ),
        SystemSymbol(
            name: "mute",
            sfSymbol: "speaker.slash",
            gtkIconName: "audio-volume-muted",
            segoeScalar: 0xE74F,
            androidDrawable: "ic_lock_silent_mode",
            textFallback: "Mute"
        ),
        SystemSymbol(
            name: "volume",
            sfSymbol: "speaker.3",
            gtkIconName: "audio-volume-high",
            segoeScalar: 0xE767,
            androidDrawable: "ic_lock_silent_mode_off",
            textFallback: "Volume"
        ),
        SystemSymbol(
            name: "microphone",
            sfSymbol: "mic",
            gtkIconName: "audio-input-microphone",
            segoeScalar: 0xE720,
            androidDrawable: "ic_btn_speak_now",
            textFallback: "Mic"
        ),
        SystemSymbol(
            name: "fastForward",
            sfSymbol: "forward",
            gtkIconName: "media-seek-forward",
            segoeScalar: 0xEB9D,
            androidDrawable: "ic_media_ff",
            textFallback: ">>"
        ),
        SystemSymbol(
            name: "next",
            sfSymbol: "forward.end",
            gtkIconName: "media-skip-forward",
            segoeScalar: 0xE893,
            androidDrawable: "ic_media_next",
            textFallback: ">|"
        ),
        SystemSymbol(
            name: "pause",
            sfSymbol: "pause",
            gtkIconName: "media-playback-pause",
            segoeScalar: 0xE769,
            androidDrawable: "ic_media_pause",
            textFallback: "||"
        ),
        SystemSymbol(
            name: "play",
            sfSymbol: "play",
            gtkIconName: "media-playback-start",
            segoeScalar: 0xE768,
            androidDrawable: "ic_media_play",
            textFallback: ">"
        ),
        SystemSymbol(
            name: "previous",
            sfSymbol: "backward.end",
            gtkIconName: "media-skip-backward",
            segoeScalar: 0xE892,
            androidDrawable: "ic_media_previous",
            textFallback: "|<"
        ),
        SystemSymbol(
            name: "rewind",
            sfSymbol: "backward",
            gtkIconName: "media-seek-backward",
            segoeScalar: 0xEB9E,
            androidDrawable: "ic_media_rew",
            textFallback: "<<"
        ),
        SystemSymbol(
            name: "camera",
            sfSymbol: "camera",
            gtkIconName: "camera-photo",
            segoeScalar: 0xE722,
            androidDrawable: "ic_menu_camera",
            textFallback: "Camera"
        ),
        SystemSymbol(
            name: "cancel",
            sfSymbol: "xmark",
            gtkIconName: "window-close",
            segoeScalar: 0xE711,
            androidDrawable: "ic_menu_close_clear_cancel",
            textFallback: "X"
        ),
        SystemSymbol(
            name: "help",
            sfSymbol: "questionmark.circle",
            gtkIconName: "help-contents",
            segoeScalar: 0xE897,
            androidDrawable: "ic_menu_help",
            textFallback: "?"
        ),
        SystemSymbol(
            name: "calendar",
            sfSymbol: "calendar",
            gtkIconName: "x-office-calendar",
            segoeScalar: 0xE787,
            androidDrawable: "ic_menu_my_calendar",
            textFallback: "Calendar"
        ),
        SystemSymbol(
            name: "settings",
            sfSymbol: "gear",
            gtkIconName: "preferences-system",
            segoeScalar: 0xE713,
            androidDrawable: "ic_menu_preferences",
            textFallback: "Settings"
        ),
        SystemSymbol(
            name: "recent",
            sfSymbol: "clock",
            gtkIconName: "document-open-recent",
            segoeScalar: 0xE823,
            androidDrawable: "ic_menu_recent_history",
            textFallback: "Recent"
        ),
        SystemSymbol(
            name: "revert",
            sfSymbol: "arrow.uturn.left",
            gtkIconName: "document-revert",
            segoeScalar: 0xE7A7,
            androidDrawable: "ic_menu_revert",
            textFallback: "Undo"
        ),
        SystemSymbol(
            name: "rotate",
            sfSymbol: "rotate.right",
            gtkIconName: "object-rotate-right",
            segoeScalar: 0xE7AD,
            androidDrawable: "ic_menu_rotate",
            textFallback: "Rotate"
        ),
        SystemSymbol(
            name: "save",
            sfSymbol: "square.and.arrow.down",
            gtkIconName: "document-save",
            segoeScalar: 0xE74E,
            androidDrawable: "ic_menu_save",
            textFallback: "Save"
        ),
        SystemSymbol(
            name: "send",
            sfSymbol: "paperplane",
            gtkIconName: "document-send",
            segoeScalar: 0xE724,
            androidDrawable: "ic_menu_send",
            textFallback: "Send"
        ),
        SystemSymbol(
            name: "sort",
            sfSymbol: "arrow.up.arrow.down",
            gtkIconName: "view-sort-ascending",
            segoeScalar: 0xE8CB,
            androidDrawable: "ic_menu_sort_alphabetically",
            textFallback: "Sort"
        ),
        SystemSymbol(
            name: "zoomIn",
            sfSymbol: "plus.magnifyingglass",
            gtkIconName: "zoom-in",
            segoeScalar: 0xE8A3,
            androidDrawable: "ic_menu_zoom",
            textFallback: "Zoom"
        ),
        SystemSymbol(
            name: "clear",
            sfSymbol: "xmark.circle",
            gtkIconName: "edit-clear",
            segoeScalar: 0xE894,
            androidDrawable: "ic_notification_clear_all",
            textFallback: "Clear"
        ),
        SystemSymbol(
            name: "reminder",
            sfSymbol: "bell",
            gtkIconName: "appointment-soon",
            segoeScalar: 0xEB50,
            androidDrawable: "ic_popup_reminder",
            textFallback: "Reminder"
        ),
        SystemSymbol(
            name: "sync",
            sfSymbol: "arrow.2.circlepath",
            // `view-refresh`, not `sync-synchronizing`. The latter is not a
            // freedesktop icon name and resolves nowhere, so this symbol was the
            // only one of the 36 that fell back to text on GtkBackend -- P51's
            // capture on 2026-09-08 drew it as the truncated string "Sy...".
            //
            // Audited the same day against the Adwaita theme shipped with this
            // host's GTK (C:/gtk4/share/icons/Adwaita, 766 icon files), trying
            // `<name>-symbolic` then `<name>` exactly as
            // `GtkBackend+Symbols.availableIconName(for:)` does: 35 of the 36
            // names resolved and this was the one that did not. Control:
            // `zzz-not-a-real-icon` -> 0, so the search was working.
            //
            // Adwaita offers two candidates and they are not the same kind of
            // thing. `emblem-synchronizing.png` is an EMBLEM -- a badge meant to
            // be composited onto a file icon, PNG only, with no symbolic variant
            // -- while `view-refresh-symbolic.svg` is the standalone action icon
            // and is the circular-arrows shape that `arrow.2.circlepath` names on
            // the SF side. `view-refresh` was free: no other row used it.
            //
            // 此處為 `view-refresh` 而非 `sync-synchronizing`。後者不是 freedesktop 的圖示名稱，
            // 解析不到任何東西，因此在 GtkBackend 上，這是 36 個符號中唯一退回文字的一個——
            // 2026-09-08 P51 的擷圖把它畫成了被截斷的字串「Sy...」。
            //
            // 同日對本機 GTK 所附的 Adwaita 主題（C:/gtk4/share/icons/Adwaita，766 個圖示檔）做了
            // 稽核，並完全比照 `GtkBackend+Symbols.availableIconName(for:)` 的順序先試
            // `<name>-symbolic` 再試 `<name>`：36 個名稱中有 35 個解析成功，而這是唯一失敗的那個。
            // 控制組：`zzz-not-a-real-icon` -> 0，證明該搜尋確實有效。
            //
            // Adwaita 提供兩個候選，而它們並非同一類東西。`emblem-synchronizing.png` 是一個
            // **emblem**——設計來疊加在檔案圖示上的角標，只有 PNG、沒有 symbolic 變體；而
            // `view-refresh-symbolic.svg` 才是獨立的動作圖示，也正是 SF 端 `arrow.2.circlepath`
            // 所指的那個環形雙箭頭形狀。`view-refresh` 未被佔用：表中沒有其他列使用它。
            gtkIconName: "view-refresh",
            segoeScalar: 0xE895,
            androidDrawable: "ic_popup_sync",
            textFallback: "Sync"
        ),
        SystemSymbol(
            name: "secure",
            sfSymbol: "lock.shield",
            gtkIconName: "security-high",
            segoeScalar: 0xEA18,
            androidDrawable: "ic_secure",
            textFallback: "Secure"
        ),
    ]
}
