// GENERATED by testapp/plan/tools/generate_symbol_table.py -- do not edit.
// Source of truth: testapp/plan/symbol-table-v1.md
//
// 由 testapp/plan/tools/generate_symbol_table.py 產生——請勿編輯。
// 真實來源:testapp/plan/symbol-table-v1.md

extension SystemSymbol {
    /// Every symbol, in the table's own order.
    /// 全部符號,依表中順序。
    public static let all: [SystemSymbol] = [
        SystemSymbol(
            name: "add",
            sfSymbol: "plus",
            gtkIconName: "list-add",
            segoeScalar: 0xE710,
            androidDrawable: "ic_input_add",
            textFallback: "+"
        ),
        SystemSymbol(
            name: "delete",
            sfSymbol: "trash",
            gtkIconName: "edit-delete",
            segoeScalar: 0xE74D,
            androidDrawable: "ic_delete",
            textFallback: "Delete"
        ),
        SystemSymbol(
            name: "warning",
            sfSymbol: "exclamationmark.triangle",
            gtkIconName: "dialog-warning",
            segoeScalar: 0xE7BA,
            androidDrawable: "ic_dialog_alert",
            textFallback: "!"
        ),
        SystemSymbol(
            name: "info",
            sfSymbol: "info.circle",
            gtkIconName: "dialog-information",
            segoeScalar: 0xE946,
            androidDrawable: "ic_dialog_info",
            textFallback: "i"
        ),
        SystemSymbol(
            name: "phone",
            sfSymbol: "phone",
            gtkIconName: "phone",
            segoeScalar: 0xE717,
            androidDrawable: "ic_dialog_dialer",
            textFallback: "Phone"
        ),
        SystemSymbol(
            name: "mail",
            sfSymbol: "envelope",
            gtkIconName: "mail-message-new",
            segoeScalar: 0xE715,
            androidDrawable: "ic_dialog_email",
            textFallback: "Mail"
        ),
        SystemSymbol(
            name: "map",
            sfSymbol: "map",
            gtkIconName: "find-location",
            segoeScalar: 0xE707,
            androidDrawable: "ic_dialog_map",
            textFallback: "Map"
        ),
        SystemSymbol(
            name: "search",
            sfSymbol: "magnifyingglass",
            gtkIconName: "system-search",
            segoeScalar: 0xE721,
            androidDrawable: "ic_menu_search",
            textFallback: "Search"
        ),
        SystemSymbol(
            name: "lock",
            sfSymbol: "lock",
            gtkIconName: "system-lock-screen",
            segoeScalar: 0xE72E,
            androidDrawable: "ic_lock_idle_lock",
            textFallback: "Lock"
        ),
        SystemSymbol(
            name: "batteryLow",
            sfSymbol: "battery.25",
            gtkIconName: "battery-low",
            segoeScalar: 0xE851,
            androidDrawable: "ic_lock_idle_low_battery",
            textFallback: "Battery"
        ),
        SystemSymbol(
            name: "power",
            sfSymbol: "power",
            gtkIconName: "system-shutdown",
            segoeScalar: 0xE7E8,
            androidDrawable: "ic_lock_power_off",
            textFallback: "Power"
        ),
        SystemSymbol(
            name: "mute",
            sfSymbol: "speaker.slash",
            gtkIconName: "audio-volume-muted",
            segoeScalar: 0xE74F,
            androidDrawable: "ic_lock_silent_mode",
            textFallback: "Mute"
        ),
        SystemSymbol(
            name: "volume",
            sfSymbol: "speaker.3",
            gtkIconName: "audio-volume-high",
            segoeScalar: 0xE767,
            androidDrawable: "ic_lock_silent_mode_off",
            textFallback: "Volume"
        ),
        SystemSymbol(
            name: "microphone",
            sfSymbol: "mic",
            gtkIconName: "audio-input-microphone",
            segoeScalar: 0xE720,
            androidDrawable: "ic_btn_speak_now",
            textFallback: "Mic"
        ),
        SystemSymbol(
            name: "fastForward",
            sfSymbol: "forward",
            gtkIconName: "media-seek-forward",
            segoeScalar: 0xEB9D,
            androidDrawable: "ic_media_ff",
            textFallback: ">>"
        ),
        SystemSymbol(
            name: "next",
            sfSymbol: "forward.end",
            gtkIconName: "media-skip-forward",
            segoeScalar: 0xE893,
            androidDrawable: "ic_media_next",
            textFallback: ">\\"
        ),
        SystemSymbol(
            name: "pause",
            sfSymbol: "pause",
            gtkIconName: "media-playback-pause",
            segoeScalar: 0xE769,
            androidDrawable: "ic_media_pause",
            textFallback: "\\"
        ),
        SystemSymbol(
            name: "play",
            sfSymbol: "play",
            gtkIconName: "media-playback-start",
            segoeScalar: 0xE768,
            androidDrawable: "ic_media_play",
            textFallback: ">"
        ),
        SystemSymbol(
            name: "previous",
            sfSymbol: "backward.end",
            gtkIconName: "media-skip-backward",
            segoeScalar: 0xE892,
            androidDrawable: "ic_media_previous",
            textFallback: "\\"
        ),
        SystemSymbol(
            name: "rewind",
            sfSymbol: "backward",
            gtkIconName: "media-seek-backward",
            segoeScalar: 0xEB9E,
            androidDrawable: "ic_media_rew",
            textFallback: "<<"
        ),
        SystemSymbol(
            name: "camera",
            sfSymbol: "camera",
            gtkIconName: "camera-photo",
            segoeScalar: 0xE722,
            androidDrawable: "ic_menu_camera",
            textFallback: "Camera"
        ),
        SystemSymbol(
            name: "cancel",
            sfSymbol: "xmark",
            gtkIconName: "window-close",
            segoeScalar: 0xE711,
            androidDrawable: "ic_menu_close_clear_cancel",
            textFallback: "X"
        ),
        SystemSymbol(
            name: "help",
            sfSymbol: "questionmark.circle",
            gtkIconName: "help-contents",
            segoeScalar: 0xE897,
            androidDrawable: "ic_menu_help",
            textFallback: "?"
        ),
        SystemSymbol(
            name: "calendar",
            sfSymbol: "calendar",
            gtkIconName: "x-office-calendar",
            segoeScalar: 0xE787,
            androidDrawable: "ic_menu_my_calendar",
            textFallback: "Calendar"
        ),
        SystemSymbol(
            name: "settings",
            sfSymbol: "gear",
            gtkIconName: "preferences-system",
            segoeScalar: 0xE713,
            androidDrawable: "ic_menu_preferences",
            textFallback: "Settings"
        ),
        SystemSymbol(
            name: "recent",
            sfSymbol: "clock",
            gtkIconName: "document-open-recent",
            segoeScalar: 0xE823,
            androidDrawable: "ic_menu_recent_history",
            textFallback: "Recent"
        ),
        SystemSymbol(
            name: "revert",
            sfSymbol: "arrow.uturn.left",
            gtkIconName: "document-revert",
            segoeScalar: 0xE7A7,
            androidDrawable: "ic_menu_revert",
            textFallback: "Undo"
        ),
        SystemSymbol(
            name: "rotate",
            sfSymbol: "rotate.right",
            gtkIconName: "object-rotate-right",
            segoeScalar: 0xE7AD,
            androidDrawable: "ic_menu_rotate",
            textFallback: "Rotate"
        ),
        SystemSymbol(
            name: "save",
            sfSymbol: "square.and.arrow.down",
            gtkIconName: "document-save",
            segoeScalar: 0xE74E,
            androidDrawable: "ic_menu_save",
            textFallback: "Save"
        ),
        SystemSymbol(
            name: "send",
            sfSymbol: "paperplane",
            gtkIconName: "document-send",
            segoeScalar: 0xE724,
            androidDrawable: "ic_menu_send",
            textFallback: "Send"
        ),
        SystemSymbol(
            name: "sort",
            sfSymbol: "arrow.up.arrow.down",
            gtkIconName: "view-sort-ascending",
            segoeScalar: 0xE8CB,
            androidDrawable: "ic_menu_sort_alphabetically",
            textFallback: "Sort"
        ),
        SystemSymbol(
            name: "zoomIn",
            sfSymbol: "plus.magnifyingglass",
            gtkIconName: "zoom-in",
            segoeScalar: 0xE8A3,
            androidDrawable: "ic_menu_zoom",
            textFallback: "Zoom"
        ),
        SystemSymbol(
            name: "clear",
            sfSymbol: "xmark.circle",
            gtkIconName: "edit-clear",
            segoeScalar: 0xE894,
            androidDrawable: "ic_notification_clear_all",
            textFallback: "Clear"
        ),
        SystemSymbol(
            name: "reminder",
            sfSymbol: "bell",
            gtkIconName: "appointment-soon",
            segoeScalar: 0xEB50,
            androidDrawable: "ic_popup_reminder",
            textFallback: "Reminder"
        ),
        SystemSymbol(
            name: "sync",
            sfSymbol: "arrow.2.circlepath",
            gtkIconName: "sync-synchronizing",
            segoeScalar: 0xE895,
            androidDrawable: "ic_popup_sync",
            textFallback: "Sync"
        ),
        SystemSymbol(
            name: "secure",
            sfSymbol: "lock.shield",
            gtkIconName: "security-high",
            segoeScalar: 0xEA18,
            androidDrawable: "ic_secure",
            textFallback: "Secure"
        ),
    ]
}
