#!/usr/bin/env python3
"""Generates SystemSymbol+Table.swift from symbol-table-v1.md.

The markdown table is the source of truth: every value in it was grepped out of
a downloaded file (the SF Symbols catalogue, the freedesktop icon-naming spec,
the Segoe Fluent Icons list, android.R.drawable) and the document carries the
citation. This script exists so that the Swift array is derived from that table
rather than typed beside it, because two hand-maintained copies of 36 rows
disagree quietly and the disagreement shows up as one wrong icon on one backend.

由 symbol-table-v1.md 產生 SystemSymbol+Table.swift。

該 markdown 表格是真實來源:其中每一個值都是從下載回來的檔案中 grep 出來的(SF Symbols 目錄、
freedesktop 圖示命名規格、Segoe Fluent Icons 清單、android.R.drawable),而該文件保有其引證。
本腳本存在的理由,是讓 Swift 陣列由那張表「導出」而非在它旁邊「另行輸入」——因為兩份手動維護的
36 列副本會安靜地彼此分歧,而那個分歧會以「某個 backend 上某一個圖示是錯的」這種形式出現。

Usage / 用法:
    python3 testapp/plan/tools/generate_symbol_table.py
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[3]
SOURCE = ROOT / "testapp/plan/symbol-table-v1.md"
TARGET = ROOT / "Sources/SwiftCrossUI/Symbols/SystemSymbol+Table.swift"


def rows():
    out = []
    for line in SOURCE.read_text().splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        # A data row starts with the symbol's number. The header, the separator
        # and the prose tables elsewhere in the document all fail this test,
        # which is why it is the test: matching on column count alone would
        # pick up the coverage tables further down the same file.
        # 資料列以該符號的編號開頭。表頭、分隔列,以及文件他處的散文表格全都通不過這項檢查——
        # 而那正是採用它的理由:只比對欄位數量的話,會把同一份檔案後段的涵蓋率表格一併撈進來。
        if len(cells) >= 7 and re.match(r"^\d+$", cells[0]):
            out.append(cells)
    return out


def quote(text):
    text = text.strip("`")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    data = rows()
    if not data:
        sys.exit(f"no data rows found in {SOURCE}")

    entries = []
    for cells in data:
        code_point = re.search(r"U\+([0-9A-Fa-f]{4,6})", cells[4])
        if not code_point:
            sys.exit(f"row {cells[0]} ({cells[1]}) has no U+ code point in {cells[4]!r}")
        entries.append(
            "        SystemSymbol(\n"
            f"            name: {quote(cells[1])},\n"
            f"            sfSymbol: {quote(cells[2])},\n"
            f"            gtkIconName: {quote(cells[3])},\n"
            f"            segoeScalar: 0x{code_point.group(1).upper()},\n"
            f"            androidDrawable: {quote(cells[5])},\n"
            f"            textFallback: {quote(cells[6])}\n"
            "        ),"
        )

    TARGET.write_text(
        "// GENERATED by testapp/plan/tools/generate_symbol_table.py -- do not edit.\n"
        "// Source of truth: testapp/plan/symbol-table-v1.md\n"
        "//\n"
        "// 由 testapp/plan/tools/generate_symbol_table.py 產生——請勿編輯。\n"
        "// 真實來源:testapp/plan/symbol-table-v1.md\n"
        "\n"
        "extension SystemSymbol {\n"
        "    /// Every symbol, in the table's own order.\n"
        "    /// 全部符號,依表中順序。\n"
        "    public static let all: [SystemSymbol] = [\n"
        + "\n".join(entries)
        + "\n    ]\n}\n"
    )
    print(f"wrote {TARGET.relative_to(ROOT)} with {len(entries)} symbols")


if __name__ == "__main__":
    main()
